'use strict';
const labels=['每日行程','同志推薦','越南洗頭','美食口袋','夜市散步'];
const $=id=>document.getElementById(id);let tab=0,day=0;let completed={};try{completed=JSON.parse(localStorage.getItem('danang-trip-v1')||'{}')}catch{}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const txt=c=>c?.text||'';const safeURL=u=>/^https:\/\/(maps\.google\.com|maps\.app\.goo\.gl)\//.test(u)?u:'';
const days=[];let current;TRIP_DATA[0].rows.slice(1).forEach((r,i)=>{if(/^D\d/.test(txt(r[0]))){current={title:txt(r[0]),rows:[]};days.push(current)}else if(current&&r.some(c=>c.text))current.rows.push({r,id:'trip-'+i})});
function card(title,fields,url,id,time=''){const done=completed[id];return `<article class="card ${done?'done':''}">${time?`<div class="time">${escapeHTML(time)}</div>`:''}<h3>${escapeHTML(title)}</h3><dl class="details">${fields.filter(f=>f[1]).map(([k,v])=>`<dt>${escapeHTML(k)}</dt><dd>${escapeHTML(v)}</dd>`).join('')}</dl><div class="actions">${safeURL(url)?`<a class="map" href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">開啟地圖 ↗</a>`:'<span></span>'}<label class="check"><input type="checkbox" data-id="${id}" ${done?'checked':''}> 已完成</label></div></article>`}
function render(){const q=$('search').value.trim().toLowerCase();$('tabs').innerHTML=labels.map((n,i)=>`<button data-tab="${i}" class="${i===tab?'active':''}" aria-pressed="${i===tab}">${n}</button>`).join('');$('days').hidden=tab!==0;$('days').innerHTML=days.map((d,i)=>`<button data-day="${i}" class="${day===i?'active':''}" aria-pressed="${day===i}">D${i+1} · ${['11/26','11/27','11/28','11/29','11/30','12/01'][i]}</button>`).join('');let out='';const match=r=>r.some(c=>txt(c).toLowerCase().includes(q));if(tab===0){$('heading').innerHTML=`<h2>${escapeHTML(q?'搜尋全部行程':days[day].title)}</h2><p class="intro">${q?'跨六天搜尋結果':'按行程順序瀏覽，地圖一鍵開啟。'}</p>`;(q?days:[days[day]]).forEach(d=>{if(q&&d.rows.some(x=>match(x.r)))out+=`<h3 class="section-title">${escapeHTML(d.title)}</h3>`;d.rows.filter(x=>match(x.r)).forEach(({r,id})=>out+=card(txt(r[1]),[['時間・費用',txt(r[3])],['備註',txt(r[4])]],r[2]?.url,id,txt(r[0])))});}else{const data=TRIP_DATA[tab];$('heading').innerHTML=`<h2>${escapeHTML(txt(data.rows[0][0]))}</h2><p class="intro">${escapeHTML(txt(data.rows[1][0]))}</p>`;const headers=data.rows[3].map(txt);data.rows.slice(4).forEach((r,i)=>{if(!r.some(c=>c.text)||!match(r))return;const populated=r.filter(c=>c.text);if(populated.length===1){out+=`<h3 class="section-title">${escapeHTML(populated[0].text)}</h3>`;return}const name=txt(r[1])||txt(r[0]);const fields=r.map((c,j)=>[headers[j]||'備註',txt(c)]).filter((f,j)=>j!==1&&!r[j]?.url&&!(j===0&&name===txt(r[0])));out+=card(name,fields,r.find(c=>c.url)?.url,'place-'+tab+'-'+i);});}$('content').className=out?'grid':'';$('content').innerHTML=out||'<p class="empty">沒有符合的結果，試試其他關鍵字。</p>';}
$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b){tab=Number(b.dataset.tab);render()}});$('days').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b){day=Number(b.dataset.day);$('search').value='';render()}});$('search').addEventListener('input',render);$('content').addEventListener('change',e=>{if(e.target.dataset.id){completed[e.target.dataset.id]=e.target.checked;try{localStorage.setItem('danang-trip-v1',JSON.stringify(completed))}catch{}e.target.closest('.card').classList.toggle('done',e.target.checked)}});render();
